name: flutter integration test

on: [push, pull_request]

jobs:
  integration_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: futureware-tech/simulator-action@v1
        with:
          model: "iPhone 8"
      - run: "flutter drive --target=integration_test/app.dart"
